### ISSUE TITLE
困惑的一个问题

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [newJcole/chrome-samesite-cookie#1]
想请教一下，跨域携带cookie假设前端加了  withCredentials: true,然后后端也允许跨域了，还有必要用这个插件吗？

因为之前就遇到一个跨域，然后自己现在的谷歌浏览器还是80版本的。我记得我之前也改过这个samesite属性。
但是我的edge浏览器是最新的，好像项目也不存在跨域的问题。但是有时候和后端联调还是会出现莫名其妙的跨域。实在是搞不懂。

**Comment by daylenjeez** [comment]
> 想请教一下，跨域携带cookie假设前端加了 withCredentials: true,然后后端也允许跨域了，还有必要用这个插件吗？
> 
> 因为之前就遇到一个跨域，然后自己现在的谷歌浏览器还是80版本的。我记得我之前也改过这个samesite属性。 但是我的edge浏览器是最新的，好像项目也不存在跨域的问题。但是有时候和后端联调还是会出现莫名其妙的跨域。实在是搞不懂。

您好～
先说结论，在 chrome/edge (edge内核是Chromium) 最新版本上，要实现cookie跨站共享还是 **需要使用该插件 或者 其他方案（反向代理等）来解决**；

如果只需要解决 客户端与服务端能够跨域请求，是不需要该插件的，只需要使用常见的跨域解决方案即可，所以说如果你在联调时发现跨域问题，此插件是无法帮助你解决跨域问题，还是说可能我理解错了，你说的跨域情况就是cookie共享失败的问题，你看需要的话可以尽可能提供更多的信息；

此插件主要是解决cookie无法跨站共享；你说的 _``withCredentials: true`` 配置同时需要配置`` Access-Control-Allow-Origin``为指定域名(``Access-Control-Allow-Origin:*``是无效的)；_  这个方案在chrome 94+版本也无效了（你说的80版本应该是可以生效的），94+版本 chrome ``samesite``属性已经完全不能配置，只能通过此插件或者其他方案去解决了。
