### ISSUE TITLE
iframe跨站Set-Cookie SameSite=Lax，cookie不能写入，这个也给解决一下呗。

### ISSUE THREAD

**Issue by biaoma** [newJcole/chrome-samesite-cookie#2]
提示：This Set-Cookie header didn't specify a "SameSite" attribute and was defaulted to "SameSite=Lax," and was blocked because it come from a cross-site response which was not the response to a top-level navigation. The Set-Cookie had to have been set with "SameSite=None" to enable cross-site usage.

**Comment by daylenjeez** [comment]
> 提示：This Set-Cookie header didn't specify a "SameSite" attribute and was defaulted to "SameSite=Lax," and was blocked because it come from a cross-site response which was not the response to a top-level navigation. The Set-Cookie had to have been set with "SameSite=None" to enable cross-site usage.

能帮忙发下 iframe页面的域名 和 嵌套iframe的域名吗？@biaoma

**Comment by biaoma** [comment]
由于我的开发环境和嵌套域名是内网域名，我在外网找个一个测试域名。

域名地址：http://www.rushi.net/a.html,嵌套域名：https://www.imooc.com/。

步骤：
第一步：打开http://www.rushi.net/a.html，然后按住f12打开开发者控制台切换到network栏目，然后点击网页上的登录-验证码登录，输入手机号和验证码，点击登录。
![微信截图_20230916170155](https://github.com/daylenjeez/chrome-samesite-cookie/assets/21099872/f065ab5b-dd1d-4784-bdfd-9d8f40c7f2b0)

第二步：图片上显示了Set-Cookie写入失败的提示。
![微信截图_20230916170035](https://github.com/daylenjeez/chrome-samesite-cookie/assets/21099872/b9d70f2b-f9ce-4209-b1fe-76a0d6bc5d87)

@daylenjeez

**Comment by daylenjeez** [comment]
hello~@biaoma ,我看了下你发的这个报错，是提示说限制了网站在 ``iframe`` 中 跨域传递cookie；
这个限制是[https://www.imooc.com](https://www.imooc.com) 服务端加的同源校验；插件没办法干涉😢，插件默认是支持在``iframe`` + ``SameSite=Lax``  下共享``cookie``的，但是服务端加了同源校验，就没办法了...

1. 我在本地测试了下服务端没做限制的情况，插件可以生效，``iframe``跨域传``cookie``不会有这个报错；
2. 同样的我在[https://www.imooc.com](https://www.imooc.com) 中嵌套 [https://www.imooc.com](https://www.imooc.com) 是可以登录成功不会有这个报错的，因为是同源的；
